### Notebook 1 – Data Understanding

understand the structure, quality and characteristics of the Brisbane bikeway count data before performing preprocessing and machine learning.

- What data is available?
- What are the important variables?
- Are there missing values?
- What preprocessing is required?

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import plotly.express as px

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

In [9]:
counts = pd.read_csv("../data/raw/bikeway-counts.csv")
locations = pd.read_csv("../data/raw/bikeway-counts-counter-locations.csv")

In [10]:
print("=" * 50)
print("Bikeway Counts")
print("=" * 50)

print(counts.shape)

print()

print("=" * 50)
print("Counter Locations")
print("=" * 50)

print(locations.shape)

==================================================
Bikeway Counts
==================================================
(1461, 71)

==================================================
Counter Locations
==================================================
(257, 31)

#### Understanding counts dataset

In [12]:
counts.head()

,Date,A001 Cyclist,A001 Pedestrian,A002 Cyclist,A002 Pedestrian,A003 Cyclist,A003 Pedestrian,A004E Cyclist,A004N Pedestrian,A005E Pedestrian,A005W Cyclist,A006 Cyclist,A006 Pedestrian,A007 Cyclist,A007 Pedestrian,A008 Cyclist,A008 Pedestrian,A009 Cyclist,A009 Pedestrian,A010 Cyclist,A010 Pedestrian,A011 Cyclist,A011 Pedestrian,A012 Cyclist,A012 Pedestrian,A013 Cyclist,A013 Pedestrian,A014 Cyclist,A014 Pedestrian,A016E Cyclist,A016E Pedestrian,A016W Cyclist,A016W Pedestrian,A017 Cyclist,A017 Pedestrian,A018 Cyclist,A018 Pedestrian,A019 Cyclist,A019 Pedestrian,A020 Cyclist,A020 Pedestrian,A021 Cyclist,A021 Pedestrian,A022 Cyclist,A023 Cyclist,A023 Pedestrian,A024 Cyclist,A024 Pedestrian,A025 Cyclist,A025 Pedestrian,A026 Cyclist,A027 Cyclist,A028 Cyclist,A028 Pedestrian,A029 Cyclist,A030 Cyclist,A030 Pedestrian,A032 Cyclist,A032 Pedestrian,A032 Scooter,A103 Cyclist,A103 Pedestrian,A200 Cyclist,A200 Scooter,A201 Cyclist,A202 Cyclist,A202 Scooter,A203 Cyclist,A203 Scooter,A204 Cyclist,A204 Scooter
0,2022-01-01,NaN,NaN,38.0,698.0,120.0,521.0,270.0,806.0,454.0,NaN,NaN,NaN,142.0,310,NaN,NaN,243.0,463.0,85.0,216.0,129.0,NaN,91.0,152.0,206.0,1277.0,NaN,NaN,80.0,531.0,163.0,1257.0,3.0,268.0,174.0,673.0,NaN,NaN,2.0,84.0,209.0,1435.0,220.0,596.0,2581.0,85.0,304.0,761.0,4023.0,166,146.0,261.0,687.0,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.0,158.0,256.0,51.0,282.0,NaN,NaN
1,2022-01-02,NaN,NaN,156.0,591.0,402.0,484.0,880.0,782.0,616.0,NaN,NaN,NaN,829.0,724,NaN,NaN,1250.0,1106.0,240.0,380.0,607.0,NaN,473.0,335.0,1051.0,2088.0,NaN,NaN,622.0,636.0,363.0,889.0,17.0,814.0,883.0,929.0,NaN,NaN,50.0,176.0,1301.0,2514.0,616.0,2382.0,4426.0,589.0,552.0,2793.0,6457.0,436,525.0,1106.0,1019.0,349.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,236.0,304.0,343.0,63.0,485.0,NaN,NaN
2,2022-01-03,NaN,NaN,152.0,614.0,402.0,349.0,888.0,692.0,582.0,NaN,NaN,NaN,801.0,600,NaN,NaN,1160.0,1006.0,310.0,340.0,638.0,NaN,403.0,374.0,993.0,1971.0,NaN,NaN,582.0,527.0,328.0,591.0,19.0,NaN,695.0,910.0,NaN,NaN,33.0,149.0,1000.0,2267.0,592.0,2149.0,3641.0,465.0,535.0,2599.0,6142.0,441,542.0,1025.0,1016.0,334.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183.0,277.0,332.0,114.0,402.0,NaN,NaN
3,2022-01-04,NaN,NaN,158.0,514.0,281.0,215.0,1041.0,681.0,446.0,NaN,NaN,NaN,578.0,399,NaN,NaN,790.0,894.0,241.0,255.0,651.0,NaN,401.0,356.0,644.0,1476.0,NaN,NaN,463.0,445.0,321.0,367.0,26.0,NaN,673.0,812.0,NaN,NaN,21.0,134.0,712.0,1860.0,646.0,1538.0,2664.0,498.0,549.0,2423.0,4298.0,434,491.0,688.0,784.0,294.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,286.0,373.0,399.0,157.0,405.0,NaN,NaN
4,2022-01-05,NaN,NaN,111.0,454.0,254.0,185.0,1011.0,766.0,475.0,NaN,NaN,NaN,588.0,462,NaN,NaN,823.0,913.0,183.0,199.0,572.0,NaN,362.0,272.0,481.0,1370.0,NaN,NaN,464.0,263.0,303.0,487.0,24.0,NaN,645.0,743.0,NaN,NaN,25.0,125.0,608.0,1886.0,618.0,1416.0,2604.0,441.0,454.0,2341.0,4089.0,448,477.0,727.0,766.0,292.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,237.0,361.0,401.0,157.0,396.0,NaN,NaN

In [13]:
locations.head()

,Site ID,Parent Site ID,Site Name,Short Name,Type,Latitude,Longitude,Start_Date,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,geolocation
0,M002E,M002,"Story Bridge (East), Kangaroo Point","Story Br, Kangaroo Pt",Manual,-27.461897,153.035827,2004.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,"-27.461897, 153.035827"
1,M002W,M002,"Story Bridge (West), Kangaroo Point","Story Br, Kangaroo Pt",Manual,-27.461891,153.035577,2004.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,"-27.461891, 153.035577"
2,M003,M003,"Riverwalk, New Farm","Riverwalk, New Farm",Manual,-27.471070,153.041141,2004.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,"-27.47107, 153.041141"
3,M004,M004,Story Bridge Underpass connecting Bowen Terrac...,Story Br Underpass connecting Bowen Terrace_Iv...,Manual,-27.461705,153.035592,2011.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"-27.461705, 153.035592"
4,M009,M009,"Kedron Brook Bikeway Nudgee Rd, Nundah","Kedron Brook Bikeway Nudgee Rd, Nundah",Manual,-27.406524,153.073747,2004.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,"-27.40652433, 153.0737474"

In [14]:
locations["Site ID"].head(20)

0      M002E
1      M002W
2       M003
3       M004
4       M009
5       M012
6      M016W
7      M020W
8      M021N
9      M024E
10     M024W
11    M026SE
12      M028
13      M029
14      M030
15      M031
16     M033W
17      M041
18     M043W
19      M045
Name: Site ID, dtype: str

In [16]:
counts.columns[:20]

Index(['Date', 'A001 Cyclist', 'A001 Pedestrian', 'A002 Cyclist', 'A002 Pedestrian', 'A003 Cyclist', 'A003 Pedestrian', 'A004E Cyclist', 'A004N Pedestrian', 'A005E Pedestrian', 'A005W Cyclist',
       'A006 Cyclist', 'A006 Pedestrian', 'A007 Cyclist', 'A007 Pedestrian', 'A008 Cyclist', 'A008 Pedestrian', 'A009 Cyclist', 'A009 Pedestrian', 'A010 Cyclist'],
      dtype='str')

In [17]:
print("Counts dataset shape:", counts.shape)
print("Locations dataset shape:", locations.shape)

Counts dataset shape: (1461, 71)
Locations dataset shape: (257, 31)

In [18]:
counts.info()

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 71 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              1461 non-null   str
 1   A001 Cyclist      1009 non-null   float64
 2   A001 Pedestrian   785 non-null    float64
 3   A002 Cyclist      395 non-null    float64
 4   A002 Pedestrian   306 non-null    float64
 5   A003 Cyclist      140 non-null    float64
 6   A003 Pedestrian   140 non-null    float64
 7   A004E Cyclist     795 non-null    float64
 8   A004N Pedestrian  1231 non-null   float64
 9   A005E Pedestrian  928 non-null    float64
 10  A005W Cyclist     606 non-null    float64
 11  A006 Cyclist      648 non-null    float64
 12  A006 Pedestrian   649 non-null    float64
 13  A007 Cyclist      1418 non-null   float64
 14  A007 Pedestrian   1461 non-null   int64
 15  A008 Cyclist      1090 non-null   float64
 16  A008 Pedestrian   753 non-null    float64
 17  A009 Cyclist      433 non-null    float64
 18  A009 Pedestrian   432 non-null    float64
 19  A010 Cyclist      968 non-null    float64
 20  A010 Pedestrian   819 non-null    float64
 21  A011 Cyclist      393 non-null    float64
 22  A011 Pedestrian   0 non-null      float64
 23  A012 Cyclist      1225 non-null   float64
 24  A012 Pedestrian   1225 non-null   float64
 25  A013 Cyclist      1206 non-null   float64
 26  A013 Pedestrian   962 non-null    float64
 27  A014 Cyclist      1320 non-null   float64
 28  A014 Pedestrian   1322 non-null   float64
 29  A016E Cyclist     979 non-null    float64
 30  A016E Pedestrian  677 non-null    float64
 31  A016W Cyclist     1205 non-null   float64
 32  A016W Pedestrian  1205 non-null   float64
 33  A017 Cyclist      1124 non-null   float64
 34  A017 Pedestrian   628 non-null    float64
 35  A018 Cyclist      842 non-null    float64
 36  A018 Pedestrian   841 non-null    float64
 37  A019 Cyclist      455 non-null    float64
 38  A019 Pedestrian   455 non-null    float64
 39  A020 Cyclist      1460 non-null   float64
 40  A020 Pedestrian   1379 non-null   float64
 41  A021 Cyclist      1378 non-null   float64
 42  A021 Pedestrian   1354 non-null   float64
 43  A022 Cyclist      1345 non-null   float64
 44  A023 Cyclist      1129 non-null   float64
 45  A023 Pedestrian   1124 non-null   float64
 46  A024 Cyclist      865 non-null    float64
 47  A024 Pedestrian   781 non-null    float64
 48  A025 Cyclist      893 non-null    float64
 49  A025 Pedestrian   894 non-null    float64
 50  A026 Cyclist      1461 non-null   int64
 51  A027 Cyclist      1459 non-null   float64
 52  A028 Cyclist      1117 non-null   float64
 53  A028 Pedestrian   714 non-null    float64
 54  A029 Cyclist      1453 non-null   float64
 55  A030 Cyclist      670 non-null    float64
 56  A030 Pedestrian   670 non-null    float64
 57  A032 Cyclist      382 non-null    float64
 58  A032 Pedestrian   382 non-null    float64
 59  A032 Scooter      382 non-null    float64
 60  A103 Cyclist      248 non-null    float64
 61  A103 Pedestrian   248 non-null    float64
 62  A200 Cyclist      738 non-null    float64
 63  A200 Scooter      739 non-null    float64
 64  A201 Cyclist      37 non-null     float64
 65  A202 Cyclist      703 non-null    float64
 66  A202 Scooter      703 non-null    float64
 67  A203 Cyclist      507 non-null    float64
 68  A203 Scooter      507 non-null    float64
 69  A204 Cyclist      480 non-null    float64
 70  A204 Scooter      480 non-null    float64
dtypes: float64(68), int64(2), str(1)
memory usage: 824.8 KB

In [19]:
counts.columns.tolist()

['Date',
 'A001 Cyclist',
 'A001 Pedestrian',
 'A002 Cyclist',
 'A002 Pedestrian',
 'A003 Cyclist',
 'A003 Pedestrian',
 'A004E Cyclist',
 'A004N Pedestrian',
 'A005E Pedestrian',
 'A005W Cyclist',
 'A006 Cyclist',
 'A006 Pedestrian',
 'A007 Cyclist',
 'A007 Pedestrian',
 'A008 Cyclist',
 'A008 Pedestrian',
 'A009 Cyclist',
 'A009 Pedestrian',
 'A010 Cyclist',
 'A010 Pedestrian',
 'A011 Cyclist',
 'A011 Pedestrian',
 'A012 Cyclist',
 'A012 Pedestrian',
 'A013 Cyclist',
 'A013 Pedestrian',
 'A014 Cyclist',
 'A014 Pedestrian',
 'A016E Cyclist',
 'A016E Pedestrian',
 'A016W Cyclist',
 'A016W Pedestrian',
 'A017 Cyclist',
 'A017 Pedestrian',
 'A018 Cyclist',
 'A018 Pedestrian',
 'A019 Cyclist',
 'A019 Pedestrian',
 'A020 Cyclist',
 'A020 Pedestrian',
 'A021 Cyclist',
 'A021 Pedestrian',
 'A022 Cyclist',
 'A023 Cyclist',
 'A023 Pedestrian',
 'A024 Cyclist',
 'A024 Pedestrian',
 'A025 Cyclist',
 'A025 Pedestrian',
 'A026 Cyclist',
 'A027 Cyclist',
 'A028 Cyclist',
 'A028 Pedestrian',
 'A029 Cyclist',
 'A030 Cyclist',
 'A030 Pedestrian',
 'A032 Cyclist',
 'A032 Pedestrian',
 'A032 Scooter',
 'A103 Cyclist',
 'A103 Pedestrian',
 'A200 Cyclist',
 'A200 Scooter',
 'A201 Cyclist',
 'A202 Cyclist',
 'A202 Scooter',
 'A203 Cyclist',
 'A203 Scooter',
 'A204 Cyclist',
 'A204 Scooter']

In [20]:
#count of each transport mode
cyclist = [c for c in counts.columns if "Cyclist" in c]

pedestrian = [c for c in counts.columns if "Pedestrian" in c]

scooter = [c for c in counts.columns if "Scooter" in c]

print(len(cyclist))

print(len(pedestrian))

print(len(scooter))

37
28
5

In [21]:
#missing values
missing = counts.isnull().sum()

missing = missing[missing > 0]

missing.sort_values(ascending=False)

A011 Pedestrian    1461
A201 Cyclist       1424
A003 Cyclist       1321
A003 Pedestrian    1321
A103 Cyclist       1213
                   ...
A020 Pedestrian      82
A007 Cyclist         43
A029 Cyclist          8
A027 Cyclist          2
A020 Cyclist          1
Length: 68, dtype: int64

In [23]:
#check possible date range
#exact 4 years of data - jan 2022 till dec 2025
counts["Date"] = pd.to_datetime(counts["Date"])

print(counts["Date"].min())

print(counts["Date"].max())

2022-01-01 00:00:00
2025-12-31 00:00:00

In [25]:
counts.duplicated().sum()
#good thing - no duplicates

np.int64(0)

In [26]:
counts.describe()

,Date,A001 Cyclist,A001 Pedestrian,A002 Cyclist,A002 Pedestrian,A003 Cyclist,A003 Pedestrian,A004E Cyclist,A004N Pedestrian,A005E Pedestrian,A005W Cyclist,A006 Cyclist,A006 Pedestrian,A007 Cyclist,A007 Pedestrian,A008 Cyclist,A008 Pedestrian,A009 Cyclist,A009 Pedestrian,A010 Cyclist,A010 Pedestrian,A011 Cyclist,A011 Pedestrian,A012 Cyclist,A012 Pedestrian,A013 Cyclist,A013 Pedestrian,A014 Cyclist,A014 Pedestrian,A016E Cyclist,A016E Pedestrian,A016W Cyclist,A016W Pedestrian,A017 Cyclist,A017 Pedestrian,A018 Cyclist,A018 Pedestrian,A019 Cyclist,A019 Pedestrian,A020 Cyclist,A020 Pedestrian,A021 Cyclist,A021 Pedestrian,A022 Cyclist,A023 Cyclist,A023 Pedestrian,A024 Cyclist,A024 Pedestrian,A025 Cyclist,A025 Pedestrian,A026 Cyclist,A027 Cyclist,A028 Cyclist,A028 Pedestrian,A029 Cyclist,A030 Cyclist,A030 Pedestrian,A032 Cyclist,A032 Pedestrian,A032 Scooter,A103 Cyclist,A103 Pedestrian,A200 Cyclist,A200 Scooter,A201 Cyclist,A202 Cyclist,A202 Scooter,A203 Cyclist,A203 Scooter,A204 Cyclist,A204 Scooter
count,1461,1009.000000,785.000000,395.000000,306.000000,140.000000,140.000000,795.000000,1231.00000,928.000000,606.000000,648.000000,649.000000,1418.000000,1461.000000,1090.000000,753.000000,433.000000,432.000000,968.000000,819.000000,393.000000,0.0,1225.000000,1225.000000,1206.000000,962.000000,1320.000000,1322.000000,979.000000,677.000000,1205.000000,1205.000000,1124.000000,628.00000,842.000000,841.000000,455.000000,455.000000,1460.000000,1379.000000,1378.000000,1354.000000,1345.000000,1129.000000,1124.000000,865.000000,781.000000,893.000000,894.000000,1461.000000,1459.000000,1117.000000,714.000000,1453.000000,670.000000,670.000000,382.000000,382.000000,382.000000,248.000000,248.000000,738.000000,739.000000,37.000000,703.000000,703.000000,507.000000,507.000000,480.000000,480.000000
mean,2024-01-01 00:00:00,2563.479683,1960.385987,104.918987,443.065359,220.014286,412.792857,778.701887,1468.00000,747.315733,763.044554,287.592593,339.201849,510.016925,573.555099,855.743119,2320.167331,557.457275,782.525463,150.990702,321.893773,512.419847,NaN,469.382041,256.869388,562.668325,1791.076923,220.891667,141.574130,633.595506,565.129985,449.965975,798.902075,18.858541,282.30414,598.629454,896.399524,2624.782418,1536.694505,22.203425,127.052937,627.798258,1843.537666,837.625279,482.360496,1596.825623,729.543353,817.921895,2520.017917,5412.401566,592.302533,669.859493,439.476276,746.619048,425.576050,557.280597,2165.971642,1323.293194,7468.591623,823.552356,531.548387,156.721774,406.834688,275.599459,240.108108,509.422475,378.465149,505.094675,779.072978,706.795833,350.127083
min,2022-01-01 00:00:00,276.000000,93.000000,2.000000,3.000000,14.000000,1.000000,6.000000,14.00000,1.000000,25.000000,2.000000,42.000000,13.000000,12.000000,17.000000,234.000000,1.000000,4.000000,7.000000,7.000000,9.000000,NaN,4.000000,13.000000,3.000000,1.000000,16.000000,3.000000,1.000000,2.000000,6.000000,30.000000,1.000000,1.00000,2.000000,4.000000,418.000000,434.000000,1.000000,17.000000,8.000000,225.000000,25.000000,2.000000,1.000000,47.000000,185.000000,11.000000,38.000000,17.000000,19.000000,6.000000,47.000000,11.000000,10.000000,269.000000,51.000000,745.000000,15.000000,140.000000,60.000000,4.000000,1.000000,96.000000,22.000000,21.000000,1.000000,6.000000,29.000000,3.000000
25%,2023-01-01 00:00:00,2232.000000,1704.000000,88.000000,370.000000,167.500000,303.250000,333.500000,919.50000,546.500000,665.000000,165.750000,289.000000,417.000000,449.000000,748.500000,1869.000000,432.000000,622.750000,121.000000,237.000000,437.000000,NaN,358.000000,195.000000,446.250000,1454.500000,177.000000,115.000000,526.000000,451.000000,369.000000,599.000000,12.000000,158.75000,515.000000,795.000000,1812.500000,1160.000000,17.000000,107.000000,533.000000,1519.250000,639.000000,70.000000,765.750000,513.000000,622.000000,1963.000000,4550.500000,450.000000,518.000000,352.000000,576.250000,291.000000,468.000000,1815.750000,1197.500000,6095.250000,723.500000,444.750000,131.000000,256.000000,210.000000,195.000000,416.500000,323.500000,365.500000,661.500000,529.750000,249.000000
50%,2024-01-01 00:00:00,2604.000000,1980.000000,108.000000,446.500000,219.000000,407.500000,797.000000,1294.00000,702.500000,781.000000,316.000000,347.000000,525.000000,593.000000,888.000000,2233.000000,547.000000,808.000000,150.000000,305.000000,539.000000,NaN,468.000000,258.000000,550.000000,1752.000000,218.000000,139.000000,650.000000,560.000000,454.000000,772.000000,18.000000,307.50000,624.000000,906.000000,2852.000000,1581.000000,22.000000,125.000000,625.000000,1801.000000,851.000000,151.000000,1243.000000,732.000000,810.000000,2504.000000,5497.000000,607.000000,687.000000,429.000000,743.000000,439.000000,550.000000,2204.000000,1362.500000,6763.000000,837.500000,536.500000,158.000000,396.500000,283.000000,255.000000,514.000000,382.000000,505.000000,793.000000,727.000000,368.500000
75%,2024-12-31 00:00:00,2996.000000,2217.000000,126.000000,528.500000,268.500000,507.750000,1163.000000,1824.00000,862.000000,880.750000,389.250000,392.000000,615.000000,702.000000,1017.000000,2665.000000,685.000000,963.250000,180.250000,377.000000,627.000000,NaN,600.000000,314.000000,665.000000,2091.250000,258.250000,164.750000,776.000000,648.000000,520.000000,950.000000,24.000000,400.00000,711.000000,1030.000000,3400.500000,1834.000000,27.000000,143.000000,727.000000,2131.500000,1049.000000,904.000000,2413.500000,956.000000,1003.000000,3148.000000,6385.750000,735.000000,834.000000,508.000000,922.000000,556.000000,654.000000,2464.250000,1478.250000,8642.500000,936.250000,629.500000,179.000000,555.250000,355.000000,277.000000,618.000000,439.500000,649.500000,911.500000,882.250000,442.000000
max,2025-12-31 00:00:00,3993.000000,4555.000000,215.000000,1465.000000,477.000000,1035.000000,2181.000000,4195.00000,2817.000000,2400.000000,546.000000,573.000000,1058.000000,1439.000000,1388.000000,6420.000000,1439.000000,1513.000000,340.000000,2754.000000,888.000000,NaN,878.000000,687.000000,1586.000000,8755.000000,463.000000,1359.000000,1228.000000,2585.000000,1327.000000,2092.000000,61.000000,921.00000,982.000000,1692.000000,4206.000000,3144.000000,62.000000,719.000000,1457.000000,4322.000000,1383.000000,2427.000000,6295.000000,1336.000000,1963.000000,4389.000000,15471.000000,1015.000000,1151.000000,1287.000000,4071.000000,789.000000,1270.000000,6950.000000,2064.000000,25242.000000,1380.000000,778.000000,388.000000,810.000000,643.000000,379.000000,867.000000,647.000000,971.000000,1462.000000,1385.000000,664.000000
std,NaN,640.988723,439.591195,35.148828,206.593961,94.577439,187.426705,481.785680,792.21714,348.802956,222.372875,123.547752,78.885627,163.639201,189.515801,236.806225,715.870012,235.009217,289.452246,53.000272,178.927550,168.549527,NaN,163.760644,86.575825,205.293866,682.452087,72.930594,62.494943,205.146822,255.281984,140.097710,287.680477,9.294744,152.73767,166.324677,209.530626,945.539523,500.569870,8.441330,42.188835,192.851066,504.164735,266.959586,579.471796,1071.093372,280.005168,258.673694,823.466422,1469.524819,184.617176,206.679908,171.480039,296.679994,157.477636,182.746000,641.241521,303.746895,2434.576930,194.483490,123.745845,38.812109,185.150706,98.748356,59.361783,139.270472,94.792237,198.248185,218.391570,254.049606,126.558652

#### Understanding locations dataset

In [27]:
locations.info()

<class 'pandas.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 31 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Site ID         257 non-null    str
 1   Parent Site ID  257 non-null    str
 2   Site Name       257 non-null    str
 3   Short Name      257 non-null    str
 4   Type            257 non-null    str
 5   Latitude        257 non-null    float64
 6   Longitude       257 non-null    float64
 7   Start_Date      236 non-null    float64
 8   2004            16 non-null     float64
 9   2005            16 non-null     float64
 10  2006            16 non-null     float64
 11  2007            16 non-null     float64
 12  2008            17 non-null     float64
 13  2009            17 non-null     float64
 14  2010            26 non-null     float64
 15  2011            32 non-null     float64
 16  2012            40 non-null     float64
 17  2013            31 non-null     float64
 18  2014            50 non-null     float64
 19  2015            64 non-null     float64
 20  2016            87 non-null     float64
 21  2017            80 non-null     float64
 22  2018            90 non-null     float64
 23  2019            104 non-null    float64
 24  2020            109 non-null    float64
 25  2021            124 non-null    float64
 26  2022            141 non-null    float64
 27  2023            116 non-null    float64
 28  2024            167 non-null    float64
 29  2025            143 non-null    float64
 30  geolocation     257 non-null    str
dtypes: float64(25), str(6)
memory usage: 87.7 KB

#### Conclusion

- The counts dataset contains daily observations from 2022–2025.
- There are 39 automatic monitoring sites.
- Each monitoring site records one or more transport modes.
- Missing values are expected due to installation dates or unavailable sensors.
- The counts dataset can be reshaped into tidy format.
- The location dataset contains metadata that can be merged later.